---
# tasks file for postgresql

- name: Install postgresql
  apt: name={{ item }} state=present
  with_items:
  - postgresql
  - postgresql-contrib
  - libpq-dev
  - php5.6-pgsql
  - python3-psycopg2

- name: Ensure the PostgreSQL service is running
  service: name=postgresql state=started enabled=yes


- name: Ensure database is created
  become_user: postgres
  become: yes
  postgresql_db: name={{ dbname }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
                 state=present

- name: Ensure user has access to the database
  become_user: postgres
  become: yes
  postgresql_user: db={{ dbname }}
                   name={{ dbuser }}
                   password={{ dbpassword }}
                   priv=ALL
                   state=present
                   encrypted=no

- name: Ensure user does not have unnecessary privileges
  become_user: postgres
  become: yes
  postgresql_user: name={{ dbuser }}
                   role_attr_flags=SUPERUSER,CREATEDB,CREATEROLE,REPLICATION
                   state=present

- name: Edit host file
#  lineinfile: dest=/etc/hosts backup=yes state=present insertafter="^ff02::2" line='127.0.0.1 phpmyadmin.localhost'
  lineinfile: dest=/etc/postgresql/9.5/main/pg_hba.conf backup=yes regexp='^local' state=absent

- name: Add local
  lineinfile: dest=/etc/postgresql/9.5/main/pg_hba.conf line={{ item }}
  with_items:
    - 'local   all             postgres                                md5'
    - 'local   all             all                                     md5'

- name: Restarted postgresql
  service: name=postgresql state=restarted
