---
# tasks file for composer

- name: Installing composer
  shell: curl -sS https://getcomposer.org/installer | php && mv -f ./composer.phar /usr/local/bin/composer
  args:
      creates: /usr/local/bin/composer

- name: Make Composer executable
  file: path=/usr/local/bin/composer mode=0755
